### ISSUE TITLE
Node example does not work

### ISSUE THREAD

**Issue by d-eisenga** [thednp/svg-path-commander#1]
The Node.js example from the readme does not seem to work. Both locally and on RunKit I get the error that `DOMMatrix` is not defined. I've added a link to the RunKit example below:

https://runkit.com/embed/l2tfdg13gmqm

**Comment by thednp** [comment]
I'm not really sure how to handle this issue, can you please suggest a possible fix?

**Comment by VisualFox** [comment]
I don't think that a bug per se. You just need to manually install and require the 'dommatrix' module before requiring 'svg-path-commander'. Maybe update the documentation?

1) 

`npm install dommatrix --save`

2) 

```
const DOMMatrix = require('dommatrix'); //for node.js
const SVGPathCommander = require('svg-path-commander');

console.log(new SVGPathCommander('M0 0l50 0l50 50z'));
```

**Comment by thednp** [comment]
@VisualFox thank you for your input. Please check the updated [README](https://github.com/thednp/svg-path-commander/blob/master/README.md) and feel free to bring more clarity to it.

Thanks

**Comment by VisualFox** [comment]
@thednp That perfect! Thank you!

**Comment by d-eisenga** [comment]
Thanks for the suggestion, but I still get the same error even when manually installing and requiring `dommatrix`:

```js
ReferenceError: DOMMatrix is not defined
    at <project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:5648
    at <project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:84
    at Object.<anonymous> (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:211)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (<project-dir>/index.js:5:26)
```
This is on both Node 12 and Node 14. Here's the `package.json` for my test project:
```json
{
  "name": "svg-test",
  "version": "1.0.0",
  "dependencies": {
    "dommatrix": "0.0.4-d",
    "svg-path-commander": "0.0.9"
  }
}
```

**Comment by thednp** [comment]
@VisualFox welp?

**Comment by VisualFox** [comment]
@thednp @d-eisenga I will look into that

**Comment by thednp** [comment]
@VisualFox please check the [WIKIs](https://github.com/thednp/svg-path-commander/wiki), I moved all documentation related content over there.

**Comment by VisualFox** [comment]
@d-eisenga I found the issue. Requiring dommatrix was not the correct solution and was only working for me for a wrong reason as I tested it inside a Jupyter notebook.

@thednp I am going to send you a PR for fixing this issue.

**Comment by thednp** [comment]
@VisualFox 
Green. Go ahead.

**Comment by VisualFox** [comment]
@thednp Done

**Comment by thednp** [comment]
Thanks, don't know how I missed that.

**Comment by thednp** [comment]
@d-eisenga I've published updated code to the clouds, can you please confirm the fix is OK? 

Thanks again guys.

**Comment by d-eisenga** [comment]
After updating I now get a new error:

```js
ReferenceError: feedFromArray is not defined
    at e.setIdentity (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:2132)
    at new e (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:361)
    at Y (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:17398)
    at U (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:18335)
    at G.transform (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:22065)
    at G.flipX (<project-dir>/node_modules/svg-path-commander/dist/svg-path-commander.min.js:2:22168)
    at Object.<anonymous> (<project-dir>/index.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```
This looks like an issue in the `dommatrix` library. The issue is that it's trying to access an unnamespaced `feedFromArray` which does not exist. Instead it should use `CSSMatrix.feedFromArray`. I fixed it in my local copy of `dommatrix` but then got the issue that `Multiply` is not defined, which had the same cause. The same was also true for `Translate`, and presumably for every other static method of `CSSMatrix` (like `Scale`, `SkewX/Y/Z`, etc) that's used. I might have time to make a PR sometime this week.

**Comment by thednp** [comment]
Thanks for reporting that.

**Comment by thednp** [comment]
@d-eisenga can you please test the latest versions (`dommatrix` and `svg-path-commander`)?

**Comment by d-eisenga** [comment]
The latest versions work :smiley:
I also tried it without manually including `dommatrix` and it still works, so the Wiki can be updated to remove that line again.

I think I'd like to add automated tests to both libraries, if you don't already have plans to do that. If I do, do you have any preference for testing frameworks?

**Comment by thednp** [comment]
Most popular should do, however I would like to keep close to d3.js and/or Bootstrap.

Thanks for testing, closing now.
